"""Excel comps workbook generation for PTBot."""

from __future__ import annotations

import json
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill

from .models import DealCandidate

BLUE = "0070C0"
BLACK = "000000"
GREEN = "00B050"
HEADER_FILL = "D9EAF7"


def load_deals(path: Path) -> list[DealCandidate]:
    """Load qualified deals from JSON."""
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("qualified deals JSON must be a list")
    return [DealCandidate.model_validate(item) for item in data]


def generate_comps_excel(qualified_deals_path: Path, output_path: Path, title: str) -> None:
    """Generate an IB-formatted precedent comps workbook."""
    deals = load_deals(qualified_deals_path)
    workbook = Workbook()
    cover = workbook.active
    cover.title = "Cover"
    cover["A1"] = title
    cover["A1"].font = Font(bold=True, size=16)
    cover["A3"] = "Generated by PTBot"
    cover["A5"] = "Qualified deals"
    cover["B5"] = len(deals)
    cover["B5"].font = Font(color=BLUE)

    comps = workbook.create_sheet("Comps Table")
    headers = [
        "Target",
        "Acquirer",
        "Date",
        "Deal Value",
        "Multiples",
        "EV/Revenue",
        "EV/EBITDA",
        "EV/ARR",
        "P/E",
        "Sources",
    ]
    for col, header in enumerate(headers, start=1):
        cell = comps.cell(row=1, column=col, value=header)
        cell.font = Font(bold=True)
        cell.fill = PatternFill(fill_type="solid", fgColor=HEADER_FILL)
    for row, deal in enumerate(deals, start=2):
        values = [
            deal.target,
            deal.acquirer,
            deal.date or "",
            deal.deal_value or "",
            "; ".join(deal.multiples),
            "",
            "",
            "",
            "",
            "; ".join(deal.source_urls),
        ]
        for col, value in enumerate(values, start=1):
            cell = comps.cell(row=row, column=col, value=value)
            cell.font = Font(color=BLUE)

    summary_row = len(deals) + 3
    comps.cell(row=summary_row, column=1, value="Mean rows use formulas when numeric data is added")
    comps.cell(row=summary_row, column=6, value=f"=AVERAGE(F2:F{max(2, len(deals) + 1)})")
    comps.cell(row=summary_row, column=6).font = Font(color=BLACK)

    benchmarks = workbook.create_sheet("Benchmarks")
    benchmarks["A1"] = "Benchmark Context"
    benchmarks["A1"].font = Font(bold=True)
    benchmarks["A3"] = "Populate from comparable benchmarks deep-dive output"

    sources = workbook.create_sheet("Sources")
    sources["A1"] = "Source URL"
    sources["A1"].font = Font(bold=True)
    source_row = 2
    for deal in deals:
        for source in deal.source_urls:
            sources.cell(row=source_row, column=1, value=source)
            sources.cell(row=source_row, column=1).font = Font(color=GREEN)
            source_row += 1

    for sheet in workbook.worksheets:
        for column_cells in sheet.columns:
            width = max(len(str(cell.value or "")) for cell in column_cells) + 2
            sheet.column_dimensions[column_cells[0].column_letter].width = min(width, 60)

    workbook.save(output_path)
